[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


# sdm_adding_card context
# regex also has Talisman compat
[[patches]]
[patches.regex]
target = "card.lua"
pattern = '''
[\t ]*function Card:add_to_deck[\s\S]*?
(?<indent>[\t ]*)if G\.GAME\.blind.*then G\.E_MANAGER:add_event\(Event\(\{ func = function\(\) G\.GAME\.blind:set_blind\(nil, true, nil\); return true end \}\)\) end\n'''
position = "after"
payload = """
if G.jokers and #G.jokers.cards > 0 then
    for i = 1, #G.jokers.cards do
        G.jokers.cards[i]:calculate_joker({sdm_adding_card = true, card = self})
    end
end

"""
line_prepend = '$indent'